### ISSUE TITLE
Exporting COCO freezes

### ISSUE THREAD

**Issue by martinkjlarsson** [basicai/xtreme1#295]
**Describe the bug**
When I export annotated data as COCO, the export never finishes. See the image below. The first export had the format Xtreme1 and succeeded. The second export had the format COCO but got stuck processing. I only annotated one image with a bounding box, so I don't expect the export to take long.

**To Reproduce**
1. Install Xtreme1 as specified in the README.
2. Annotate one of the default cat images with a bounding box.
3. Export annotated images in COCO format.

**Expected behavior**
A zip-file with annotations in COCO format similar to when exporting in Xtreme1 format.

**Screenshots**
![image](https://github.com/user-attachments/assets/b0404b0d-c327-45c5-8f7a-2bae844d6b44)

**Desktop:**
 - OS: Ubuntu 22.04.1 LTS running on Windows (WSL).
 - Browser: Firefox (132.0) and Chrome (130.0.6723.92)
 - Version: xtreme1-v091

**Comment by Luca120420** [comment]
same problem. Did you find a solution?

**Comment by martinkjlarsson** [comment]
No solution yet, but this exception seems to occur on the backend when starting the export:
```
Exception in thread "pool-1-thread-3" cn.hutool.core.io.IORuntimeException: NoSuchFileException: /tmp/xtreme1/Image Trial-20241105123032/image
        at cn.hutool.core.io.file.PathUtil.moveContent(PathUtil.java:531)
        at cn.hutool.core.io.file.PathUtil.move(PathUtil.java:494)
        at ai.basic.x1.usecase.ExportUseCase.getDataAndUpload(ExportUseCase.java:152)
        at ai.basic.x1.usecase.ExportUseCase.asyncExportDataZip(ExportUseCase.java:114)
        at ai.basic.x1.usecase.DataInfoUseCase.lambda$export$18(DataInfoUseCase.java:540)
        at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:59)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.NoSuchFileException: /tmp/xtreme1/Image Trial-20241105123032/image
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2717)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
        at cn.hutool.core.io.file.PathUtil.moveContent(PathUtil.java:527)
        ... 8 more
```

**Comment by martinkjlarsson** [comment]
I tried running it on another computer (Ubuntu 22.04.4 LTS), but the issue persists. Any help would be most welcomed.

**Comment by martinkjlarsson** [comment]
This seems to have been fixed by [4543067](https://github.com/xtreme1-io/xtreme1/commit/4543067116a37197bd981359aa56adffbed9f564) and is available on the main branch.

**Comment by lumax90** [comment]
> This seems to have been fixed by [4543067](https://github.com/xtreme1-io/xtreme1/commit/4543067116a37197bd981359aa56adffbed9f564) and is available on the main branch.

did you manage to get export with new updates? issue still persist on my local. even tho I rebuild it.

**Comment by martinkjlarsson** [comment]
@lumax90, yes, it is working for me. I added a polygon to a cat image, exported it to COCO, and got a ZIP file with a single JSON in COCO format. The image was not included in the ZIP, but a URL is provided in the COCO file for downloading.
